config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations" } #for reg among controllers look at reg ctrl first 

  root 'welcome#index'

  get 'profile' => 'users#profile' 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # validates :username, :presence => true, :uniqueness => true 
  #
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user! 
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController


  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up).push(:username) 
    devise_parameter_sanitizer.for(:account_update).push(:username) 

  end


end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile

  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ft" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <% if current_user %>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">FinanceTracker</a>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav col-md-6">
              <li><%= link_to "My Profile", edit_registration_path(current_user) %></li>
              <li><%= link_to "Link3", "/path3" %></li>
            </ul>
            <ul class="nav navbar-right col-md-4">
              <li class="col-md-8 user-name text-right">
                <i class="fa fa-user"></i>
                <%= current_user.username.present? ? current_user.username : current_user.email %>
              </li>
              <li class="col-md-4 logout"><%= link_to("Logout", destroy_user_session_path,
                                                      class: 'btn btn-xs btn-danger', method: :delete) %></li>
            <% end %>
          </div>
      </div>
    </div>
    

      <div class="container">
        <div class="row">
          <div class="col-lg-9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

        <footer>
          <p>&copy; Company 2016</p>
        </footer>

      </div> <!-- /container -->

  </body>
</html>

app/views/users/profile.html.haml
%h1 My profile 

app/views/welcome/index.html.haml
%h2 Hello there

= link_to "Log out", destroy_user_session_path, method: :delete 